plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "M:\\port\\Digital-Showcase\\apps\\api-server"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]